### ISSUE TITLE
Download .GPX returns error

### ISSUE THREAD

**Issue by HansDeLeenheer** [RobTS/BlueBoatLog-Support#24]
Click 3 dots for menu
<img width="641" alt="image" src="https://user-images.githubusercontent.com/21191298/193412086-28b97296-1957-4a67-838f-36a80bb35d00.png">

Select Download GPX
<img width="658" alt="Screenshot 2022-10-01 at 15 42 16" src="https://user-images.githubusercontent.com/21191298/193412415-eaa4f6e9-3c80-40fa-a21c-bc44b178233b.png">

<img width="517" alt="image" src="https://user-images.githubusercontent.com/21191298/193412036-b1b09d91-3c7d-4b89-8c80-61670385cd46.png">

**Comment by arjun-gopalratnam** [comment]
I have experienced the same issue. If you grab the route id from the url and go to api.blueboatlog.com/v1/trip/{route_id} then it downloads correctly. 

The json field gpx is created by https://blueboatlog.com/static/js/main.f04e2a2e.js so I think the bug is in that field.

**Comment by RobTS** [comment]
I had been wondering for a while why this did not work any longer and finally got around to investigating it. 

At some point, I changed how entities were converted from there internal to their external representations. During this change, I used the wrong (mistakenly allowed) field for the ID in the `gpx` property. There are tests for the gpx feature, but they only test for the presence of a string in the field and follow the gpx url of a trip only by reconstructing it from the ID instead of using the link provided.

The issue has now been fixed and the test adapted to ensure this will not break in the future, it is already live. Thanks for the help, everyone!
